// <auto-generated />
using API.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Core.Models.Community", b =>
                {
                    b.Property<int>("CommunityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("CommunityId");

                    b.ToTable("Communities");

                    b.HasData(
                        new
                        {
                            CommunityId = 1,
                            Description = "Somos una comunidad amante de la creatividad y la tecnología en sus diferentes fases que busca fomentar, inspirar y motivar el desarrollo personal y profesional de personas interesadas. Sin importar la tecnología o el sector, siempre estamos unidos. La Comarca reúne la creatividad de diferentes sectores e industrias en un mismo entorno, con la visión de ayudar a crecer profesionalmente a nuevos líderes de la innovación.",
                            Name = "La Comarca"
                        },
                        new
                        {
                            CommunityId = 2,
                            Description = "Somos una comunidad de mujeres apasionadas por la tecnología, profesionales en distintas áreas de las TIC que buscan inspirar, motivar, involucrar y educar a más chicas en el área, a través de acciones de capacitación y coaching para niñas y mujeres interesadas.",
                            Name = "Mujeres TICs RD"
                        },
                        new
                        {
                            CommunityId = 3,
                            Description = @".NET Dominicana es una comunidad abierta a todos los desarrolladores en el país interesados en aprender y expandir sus conocimientos sobre las tecnologías Microsoft .NET y todo lo que tiene para ofrecer, todos los meses realizamos eventos elegidos por la comunidad. 
 El objetivo es hacer nuevos amigos, aprender algo nuevo cada mes de los miembros de nuestra comunidad y compartir esto con nuestro entorno tecnológico.",
                            Name = ".NET Dominicana"
                        },
                        new
                        {
                            CommunityId = 4,
                            Description = "Somos un grupo amante de las tecnologías propias del área de datos, desde la administración hasta analítica avanzada.",
                            Name = "Aprendiendo BD con SQL Server"
                        },
                        new
                        {
                            CommunityId = 5,
                            Description = "Un lugar donde tratar temas relacionados al Open Source, Software Libre y distribuciones GNU/Linux.",
                            Name = "Linux Dominicana"
                        },
                        new
                        {
                            CommunityId = 6,
                            Description = "Usergroup de Experiencia de Usuario y Diseño de Interfaces de República Dominicana.",
                            Name = "UI / UX Dominicana"
                        },
                        new
                        {
                            CommunityId = 7,
                            Description = "Esta es una comunidad de desarrolladores dominicanos, para conocer quiénes somos, en qué estamos, y de paso compartir temas, ayudarnos unos a otros a solucionar problemas que no encontremos en MSDN o StackOverflow, como por ejemplo problemas relevantes al desarrollo local, y publicar ofertas de trabajo.",
                            Name = "Developers Dominicanos"
                        },
                        new
                        {
                            CommunityId = 8,
                            Description = "Google Developer Groups Santo Domingo",
                            Name = "GDG Santo Domingo"
                        },
                        new
                        {
                            CommunityId = 9,
                            Description = "Somos un grupo de apasionados que deseamos compartir y promover los conocimientos de metodologias agiles para el beneficio de la comunidad.",
                            Name = "Agile Dominicana"
                        },
                        new
                        {
                            CommunityId = 10,
                            Description = "Vamos a beber cerveza y tal vez hablar de JavaScript.",
                            Name = "fria.js"
                        },
                        new
                        {
                            CommunityId = 11,
                            Description = "Es un evento de tecnología donde los participantes aprenden acerca de los temas tecnológicos de vanguardia, y donde pueden conocer otras personas que compartan sus intereses.",
                            Name = "TECHNOLOGY INNOVATION SUMMIT"
                        },
                        new
                        {
                            CommunityId = 12,
                            Description = @"CDC reune a profesionales de software y emprendedores de diferentes idiomas, plataformas e industrias. 
 Los participantes tienen la oportunidad de compartir, participar y aprender sobre temas de tendencias que están configurando el futuro de las TI y las empresas, hoy.",
                            Name = "Caribbean Developers Conference"
                        },
                        new
                        {
                            CommunityId = 13,
                            Description = "CodeCampSDQ es una conferencia técnica con el objetivo primordial de educar a la comunidad de profesionales de TI en el Caribe en temas como: Desarrollo móvil y Web, Cloud Computing, DevOps, servicios cognitivos, entre otros.",
                            Name = "CodeCampSDQ"
                        },
                        new
                        {
                            CommunityId = 14,
                            Description = "Formado por emprendedores, H / F da cabida a programadores, desarrolladores de tecnología, emprendedores y todos aquellos amantes de las tecnologías que buscan emprender un proyecto y no saben por dónde empezar.Todo se trata del “networking” ¿Quiénes ampliar tu red de contactos ? entonces “Hackers & Founders” es donde debes estar.",
                            Name = "Hackers and Founders"
                        },
                        new
                        {
                            CommunityId = 15,
                            Description = "Surge como una iniciativa a compartir conocimientos sobre herramientas FOSS entre jóvenes profesionales, con el fin de aumentar la calidad de los servicios técnicos.",
                            Name = "Open Saturday Conference"
                        },
                        new
                        {
                            CommunityId = 16,
                            Description = "“Mujeres Cambiando el Mundo - MCM”, o su versión en inglés “Women Changing the World - WCW”, con el lema: Por más chicas en Ciencia y Tecnología!. Busca a través de una serie de charlas y paneles, poder ayudar a las chicas a que vean la carrera de tecnología como una oportunidad, de que ellas tienen espacio y que pueden desarrollarse y llegar tan lejos como se lo propongan.",
                            Name = "Mujeres Cambiando el Mundo"
                        },
                        new
                        {
                            CommunityId = 17,
                            Description = "Odoo Dominicana es una comunidad, que reúne personas de diferentes disciplinas de negocios, con la finalidad de compartir el conocimiento en el desarrollo de soluciones tecnológicas que faciliten los procesos en las empresas.",
                            Name = "Oddo Dominicana"
                        },
                        new
                        {
                            CommunityId = 18,
                            Description = "Python Interest Group in the Dominican Republic If you want to enjoy discounts on o'reilly just use the 50% Discount with the ebooks and 40% with the printed media using the code PCBW on your purchases at http://shop.oreilly.com/",
                            Name = "Python Dominicana"
                        },
                        new
                        {
                            CommunityId = 19,
                            Description = "Capitulo de Owasp Republica Dominicana ",
                            Name = "OWASP RD"
                        });
                });

            modelBuilder.Entity("API.Core.Models.CommunityMember", b =>
                {
                    b.Property<int>("CommunityId");

                    b.Property<int>("MemberId");

                    b.HasKey("CommunityId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("CommunityMembers");

                    b.HasData(
                        new
                        {
                            CommunityId = 12,
                            MemberId = 1
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 1
                        },
                        new
                        {
                            CommunityId = 14,
                            MemberId = 1
                        },
                        new
                        {
                            CommunityId = 18,
                            MemberId = 1
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 2
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 2
                        },
                        new
                        {
                            CommunityId = 14,
                            MemberId = 2
                        },
                        new
                        {
                            CommunityId = 5,
                            MemberId = 3
                        },
                        new
                        {
                            CommunityId = 14,
                            MemberId = 3
                        },
                        new
                        {
                            CommunityId = 15,
                            MemberId = 3
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 4
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 4
                        },
                        new
                        {
                            CommunityId = 4,
                            MemberId = 4
                        },
                        new
                        {
                            CommunityId = 11,
                            MemberId = 4
                        },
                        new
                        {
                            CommunityId = 14,
                            MemberId = 4
                        },
                        new
                        {
                            CommunityId = 5,
                            MemberId = 5
                        },
                        new
                        {
                            CommunityId = 11,
                            MemberId = 5
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 5
                        },
                        new
                        {
                            CommunityId = 18,
                            MemberId = 5
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 6
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 6
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 6
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 6
                        },
                        new
                        {
                            CommunityId = 14,
                            MemberId = 6
                        },
                        new
                        {
                            CommunityId = 15,
                            MemberId = 6
                        },
                        new
                        {
                            CommunityId = 16,
                            MemberId = 6
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 7
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 7
                        },
                        new
                        {
                            CommunityId = 3,
                            MemberId = 7
                        },
                        new
                        {
                            CommunityId = 11,
                            MemberId = 7
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 7
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 7
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 8
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 8
                        },
                        new
                        {
                            CommunityId = 3,
                            MemberId = 8
                        },
                        new
                        {
                            CommunityId = 4,
                            MemberId = 8
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 8
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 8
                        },
                        new
                        {
                            CommunityId = 14,
                            MemberId = 8
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 9
                        },
                        new
                        {
                            CommunityId = 3,
                            MemberId = 9
                        },
                        new
                        {
                            CommunityId = 4,
                            MemberId = 9
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 9
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 9
                        },
                        new
                        {
                            CommunityId = 14,
                            MemberId = 9
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 10
                        },
                        new
                        {
                            CommunityId = 18,
                            MemberId = 10
                        },
                        new
                        {
                            CommunityId = 5,
                            MemberId = 10
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 11
                        },
                        new
                        {
                            CommunityId = 3,
                            MemberId = 11
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 11
                        },
                        new
                        {
                            CommunityId = 16,
                            MemberId = 11
                        },
                        new
                        {
                            CommunityId = 3,
                            MemberId = 12
                        },
                        new
                        {
                            CommunityId = 5,
                            MemberId = 12
                        },
                        new
                        {
                            CommunityId = 11,
                            MemberId = 12
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 12
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 12
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 13
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 13
                        },
                        new
                        {
                            CommunityId = 3,
                            MemberId = 13
                        },
                        new
                        {
                            CommunityId = 11,
                            MemberId = 13
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 13
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 13
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 14
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 14
                        },
                        new
                        {
                            CommunityId = 6,
                            MemberId = 14
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 14
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 14
                        },
                        new
                        {
                            CommunityId = 14,
                            MemberId = 14
                        },
                        new
                        {
                            CommunityId = 15,
                            MemberId = 14
                        },
                        new
                        {
                            CommunityId = 16,
                            MemberId = 14
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 15
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 15
                        },
                        new
                        {
                            CommunityId = 12,
                            MemberId = 15
                        },
                        new
                        {
                            CommunityId = 13,
                            MemberId = 15
                        },
                        new
                        {
                            CommunityId = 14,
                            MemberId = 15
                        },
                        new
                        {
                            CommunityId = 15,
                            MemberId = 15
                        },
                        new
                        {
                            CommunityId = 16,
                            MemberId = 15
                        },
                        new
                        {
                            CommunityId = 19,
                            MemberId = 15
                        },
                        new
                        {
                            CommunityId = 1,
                            MemberId = 16
                        },
                        new
                        {
                            CommunityId = 2,
                            MemberId = 16
                        },
                        new
                        {
                            CommunityId = 3,
                            MemberId = 16
                        },
                        new
                        {
                            CommunityId = 4,
                            MemberId = 16
                        },
                        new
                        {
                            CommunityId = 10,
                            MemberId = 16
                        });
                });

            modelBuilder.Entity("API.Core.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<double>("Salary");

                    b.Property<int>("TechnologyId");

                    b.HasKey("MemberId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            Name = "Andres Pineda",
                            Salary = 200000.0,
                            TechnologyId = 1
                        },
                        new
                        {
                            MemberId = 2,
                            Name = "Claudio Sanchez",
                            Salary = 188300.0,
                            TechnologyId = 1
                        },
                        new
                        {
                            MemberId = 3,
                            Name = "Victor Recio",
                            Salary = 180000.0,
                            TechnologyId = 2
                        },
                        new
                        {
                            MemberId = 4,
                            Name = "Stanley Lara",
                            Salary = 163500.0,
                            TechnologyId = 1
                        },
                        new
                        {
                            MemberId = 5,
                            Name = "Shailyn Ortíz",
                            Salary = 151000.0,
                            TechnologyId = 4
                        },
                        new
                        {
                            MemberId = 6,
                            Name = "Yulissa Mateo",
                            Salary = 150000.0,
                            TechnologyId = 1
                        },
                        new
                        {
                            MemberId = 7,
                            Name = "Ángel García",
                            Salary = 140000.0,
                            TechnologyId = 1
                        },
                        new
                        {
                            MemberId = 8,
                            Name = "Luis Matos",
                            Salary = 131900.0,
                            TechnologyId = 8
                        },
                        new
                        {
                            MemberId = 9,
                            Name = "Charlin Agramonte",
                            Salary = 145000.0,
                            TechnologyId = 8
                        },
                        new
                        {
                            MemberId = 10,
                            Name = "Jearel Alcántara",
                            Salary = 120000.0,
                            TechnologyId = 2
                        },
                        new
                        {
                            MemberId = 11,
                            Name = "Leomaris Reyes",
                            Salary = 120000.0,
                            TechnologyId = 8
                        },
                        new
                        {
                            MemberId = 12,
                            Name = "Yhorby Matías",
                            Salary = 130200.0,
                            TechnologyId = 1
                        },
                        new
                        {
                            MemberId = 13,
                            Name = "Emmanuel Toribio",
                            Salary = 150000.0,
                            TechnologyId = 1
                        },
                        new
                        {
                            MemberId = 14,
                            Name = "Kenny Beltre",
                            Salary = 120000.0,
                            TechnologyId = 6
                        },
                        new
                        {
                            MemberId = 15,
                            Name = "Saira Isaac Hermandez",
                            Salary = 145000.0,
                            TechnologyId = 2
                        },
                        new
                        {
                            MemberId = 16,
                            Name = "Adonis Mendoza",
                            Salary = 110000.0,
                            TechnologyId = 5
                        });
                });

            modelBuilder.Entity("API.Core.Models.Technology", b =>
                {
                    b.Property<int>("TechnologyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("TechnologyId");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            TechnologyId = 1,
                            Name = "Microsoft"
                        },
                        new
                        {
                            TechnologyId = 2,
                            Name = "Linux"
                        },
                        new
                        {
                            TechnologyId = 3,
                            Name = "Kotlin"
                        },
                        new
                        {
                            TechnologyId = 4,
                            Name = "Python"
                        },
                        new
                        {
                            TechnologyId = 5,
                            Name = "Javascript"
                        },
                        new
                        {
                            TechnologyId = 6,
                            Name = "Sketch"
                        },
                        new
                        {
                            TechnologyId = 7,
                            Name = "Docker"
                        },
                        new
                        {
                            TechnologyId = 8,
                            Name = "Xamarin"
                        });
                });

            modelBuilder.Entity("API.Core.Models.CommunityMember", b =>
                {
                    b.HasOne("API.Core.Models.Community", "Community")
                        .WithMany("CommunityMembers")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Core.Models.Member", "Member")
                        .WithMany("CommunityMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Core.Models.Member", b =>
                {
                    b.HasOne("API.Core.Models.Technology", "Technology")
                        .WithMany("Members")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
